server:
  port: 8181
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://172.31.24.168:3306/dms?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
#    url: jdbc:oracle:thin:@192.168.182.100:1521:CDSP
#    username: c##usr_ysj
#    password: wisedu
  redis:
    port: 6379
    # Redis服务器地址
    host: 127.0.0.1
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 5000ms

mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.dongms.myspringboot
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
